/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mshri;

public class App {
    public String getGreeting() {
        return "Hello World! \n\t Imported in eclipse";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
